[project]
name = "qopy"
authors = [{ name = "Zacharie Van Herstraeten", email = "zacharie.van-herstraeten@inria.fr" }]
version = "0.1"
dependencies = [
    "matplotlib>=3.10.3,<4.0",
    "mpmath>=1.3.0,<2.0",
    "numpy>=2.2.6,<3.0",
    "scikit-image>=0.25.2,<1.0",
    "scipy>=1.15.3,<2.0",
]
